export const VISABILITY_ACTIONS = {
    SET_VISABILITY_FILTER: 'SET_VISABILITY_FILTER',
    FILTERS: {
        COMPLETED: 'COMPLETED',
        VISIBLE_ALL: 'VISIBLE_ALL',
        NOT_COMPLETED: 'NOT_COMPLETED',
    }
};